# Markdown
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup

title:            MForever78
tagline:          'Code Blog'
description:      'Code about everything. Everything about code.'
url:              http://code.mforever78.com

author:
  name:           'Code Blog'
  url:            http://mforever78.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/MForever78/MForever78.github.io
