# Markdown
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup

title:            MForever78
tagline:          'Code Blog'
description:      'Code about everything. Everything about code.'
url:              http://MForever78.github.io

author:
  name:           'Code Blog'
  url:            https://MForever78.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/MForever78/MForever78.github.io
