# Permalinks
permalink:        pretty

# Setup

title:            MForever78
tagline:          'Code Blog'
description:      'Code about everything. Everything about code.'
url:              http://code.mforever78.com

author:
  name:           'Code Blog'
  url:            http://mforever78.com

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/MForever78/MForever78.github.io
