# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'MForever78'
tagline:          'Code Blog'
description:      'Code about everything. Everything about code.'
url:              http://MForever78.github.io

author:
  name:           'MForever78'
  url:            https://MForever78.com

paginate:         5

# Custom vars
version:          2.0.0

github:           https://github.com/MForever78
  repo:           https://github.com/MForever78/MForever78.github.io
